import type { Lang } from "@/lib/seo";

export const routes = {
  restaurants: "/sectors/food-beverage/restaurants",
  chains: "/sectors/chains",
  retail: "/sectors/retail",
  pos: "/solutions/pos",
  kitchen: "/solutions/kitchen",
  ordering: "/solutions/online-ordering",
  payments: "/solutions/payments",
  hardware: "/solutions/verifone",
  equipment: "/solutions/equipment",
  companion: "/solutions/kitchen-companion",
} as const;

/** Product families and their included features, shared by navigation and footer. */
export const productNavigation = [
  { key: "pos", href: routes.pos, plan: "pos", detail: null },
  { key: "ordering", href: routes.ordering, plan: "ordering", detail: null },
  {
    key: "restaurantPlan",
    href: routes.restaurants,
    plan: "restaurant",
    detail: null,
  },
  {
    key: "kitchen",
    href: routes.kitchen,
    plan: "kitchen",
    detail: "companion",
  },
  {
    key: "completePlan",
    href: "/pricing#plan-complete",
    plan: "complete",
    detail: null,
  },
] as const;

export const ui = {
  he: {
    solutions: "פתרונות",
    businesses: "לפי סוג העסק",
    products: "המוצרים שלנו",
    pricing: "מחירים",
    help: "מרכז עזרה",
    login: "כניסה לחשבון",
    demo: "לתיאום הדגמה",
    menu: "תפריט",
    close: "סגירה",
    skip: "דילוג לתוכן",
    language: "שפה",
    restaurants: "מסעדות ובתי קפה",
    chains: "רשתות וקבוצות מסעדות",
    retail: "חנויות ועסקים",
    pos: "Foody קופה",
    restaurantPlan: "Foody מסעדה",
    completePlan: "Foody מסעדה ומטבח",
    hardwarePayments: "ציוד ותשלומים",
    included: "כלול במסלול",
    viewPlan: "לפרטי המסלול והמחיר",
    kitchen: "Foody Kitchen",
    ordering: "Foody הזמנות",
    payments: "סליקה ותשלומים",
    hardware: "מסופי Verifone",
    equipment: "ציוד ומדפסות",
    companion: "Foody Companion",
    partner: "שותף ומפיץ רשמי של Verifone",
    discover: "לגלות את הפתרון",
    contact: "דברו איתנו",
    resources: "מידע ושירות",
    privacy: "פרטיות",
    terms: "תנאי שימוש",
    allRights: "כל הזכויות שמורות.",
    country: "נבנה לעסקים בישראל",
    footer:
      "מההזמנה הראשונה ועד לסניף הבא. הקופה, התשלומים והכלים שמקדמים את העסק שלכם.",
    ctaTitle: "הצעד הבא של העסק מתחיל כאן.",
    ctaText:
      "בואו נראה לכם איך Foody עובד בעסק שלכם, ונבנה יחד הצעה לקופה, לחומרה ולסליקה.",
    faq: "שאלות שעולות לפני שמתחילים",
    related: "עוד כלים לעסק שלכם",
    source: "מפרט היצרן",
    availability:
      "הדגמים, אפשרויות החיבור ואמצעי התשלום כפופים לזמינות ולהתאמה לספק הסליקה בישראל.",
  },
  fr: {
    solutions: "Solutions",
    businesses: "Votre activité",
    products: "Nos produits",
    pricing: "Tarifs",
    help: "Centre d’aide",
    login: "Connexion",
    demo: "Demander une démo",
    menu: "Menu",
    close: "Fermer",
    skip: "Aller au contenu",
    language: "Langue",
    restaurants: "Restaurants et cafés",
    chains: "Chaînes et groupes",
    retail: "Commerces et boutiques",
    pos: "Foody Caisse",
    restaurantPlan: "Foody Restaurant",
    completePlan: "Foody Restaurant & Cuisine",
    hardwarePayments: "Matériel et paiements",
    included: "Inclus dans l’offre",
    viewPlan: "Voir l’offre et son tarif",
    kitchen: "Foody Cuisine",
    ordering: "Foody Commandes",
    payments: "Paiements et slika",
    hardware: "Terminaux Verifone",
    equipment: "Matériel et imprimantes",
    companion: "Foody Compagnon",
    partner: "Partenaire et distributeur officiel Verifone",
    discover: "Découvrir la solution",
    contact: "Nous contacter",
    resources: "Ressources",
    privacy: "Confidentialité",
    terms: "Conditions d’utilisation",
    allRights: "Tous droits réservés.",
    country: "Pensé pour les entreprises en Israël",
    footer:
      "De votre première commande à votre prochaine ouverture. La caisse, les paiements et les outils pour faire grandir votre activité.",
    ctaTitle: "Votre prochaine étape commence ici.",
    ctaText:
      "Découvrez Foody avec une démo adaptée à votre activité et une proposition qui réunit logiciel, matériel et slika.",
    faq: "Les réponses avant de vous lancer",
    related: "D’autres outils pour votre activité",
    source: "Fiche du fabricant",
    availability:
      "Modèles, connectivité et moyens de paiement selon disponibilité et compatibilité avec votre prestataire en Israël.",
  },
  en: {
    solutions: "Solutions",
    businesses: "Your business",
    products: "Our products",
    pricing: "Pricing",
    help: "Help center",
    login: "Sign in",
    demo: "Book a demo",
    menu: "Menu",
    close: "Close",
    skip: "Skip to content",
    language: "Language",
    restaurants: "Restaurants & cafés",
    chains: "Restaurant groups",
    retail: "Shops & businesses",
    pos: "Foody POS",
    restaurantPlan: "Foody Restaurant",
    completePlan: "Foody Restaurant & Kitchen",
    hardwarePayments: "Hardware and payments",
    included: "Included in the plan",
    viewPlan: "View the plan and price",
    kitchen: "Foody Kitchen",
    ordering: "Foody Orders",
    payments: "Payments & processing",
    hardware: "Verifone terminals",
    equipment: "Hardware and printers",
    companion: "Foody Companion",
    partner: "Official Verifone partner & reseller",
    discover: "Explore the solution",
    contact: "Contact us",
    resources: "Resources",
    privacy: "Privacy",
    terms: "Terms of service",
    allRights: "All rights reserved.",
    country: "Built for businesses in Israel",
    footer:
      "From your first order to your next location. The POS, payments and tools to move your business forward.",
    ctaTitle: "Your next chapter starts here.",
    ctaText:
      "See Foody in action with a demo built around your business and a proposal covering software, hardware and payment processing.",
    faq: "A few things you might be wondering",
    related: "More tools for your business",
    source: "Manufacturer specifications",
    availability:
      "Models, connectivity and payment methods depend on availability and compatibility with your payment provider in Israel.",
  },
} satisfies Record<Lang, Record<string, string>>;
